# Generated by Django 3.2.12 on 2024-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.PositiveIntegerField()),
                ('userID', models.IntegerField()),
                ('timeSubmitted', models.DateTimeField(auto_now_add=True)),
                ('correctAnswers', models.PositiveIntegerField()),
                ('totalQuestions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerID', models.PositiveIntegerField()),
                ('questionID', models.PositiveIntegerField()),
                ('answer', models.CharField(max_length=100)),
                ('isCorrect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.PositiveIntegerField()),
                ('choiceAnswer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.PositiveIntegerField()),
                ('correctAnswer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.PositiveIntegerField()),
                ('answer', models.CharField(max_length=100)),
                ('nextQuestionID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.PositiveIntegerField()),
                ('questionText', models.CharField(max_length=300)),
                ('isChoice', models.BooleanField()),
                ('multimedia', models.BinaryField()),
                ('dynamicNext', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=100)),
                ('quizOwner', models.PositiveIntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('firstQuestion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
